api_version = "2025-10"

[[extensions]]
name = "delivery-info"
handle = "delivery-info"
uid = "1ea5a9db-75f7-fbea-f096-47f6bdda664298823366"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
# ✅ attributes を読むだけなら network_access は不要（fetch しないため）
# network_access = true
